### ISSUE TITLE
Spotify icon is broken with rsvg-convert version 2.40.12 in Arch Linux

### ISSUE THREAD

**Issue by amjames** [tiliado/nuvolaplayer#180]
The application icon in gnome is broken for the spotify app.  It shows a small spotify icon with the wrong colors that is localized to the top-right corner of the icon frame. 

Should look like this: 

![icon](https://cloud.githubusercontent.com/assets/9041474/11047673/c5423e0e-8701-11e5-8b6c-bd65c03bb89a.jpg)

Actually looks like this: 

![icon](https://cloud.githubusercontent.com/assets/9041474/11047678/ceb38006-8701-11e5-8348-2744c10fc240.png)

But the image is shrunk and not centered. 

Not a serious bug, but very ugly gives the impression of a glitched application

**Comment by fenryxo** [comment]
Hello @amjames. Thanks for taking the time to report this issue. I need more information to investigate it further:

* Your Linux distribution and its version.
* Version of GNOME.
* Where exactly is the icons shown?

See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.

**Comment by amjames** [comment]
> Your Linux distribution and its version

Arch-Linux 4.2.5-1

> Version of Gnome
 
3.18.1

> Where exactly is the icons shown?

- In the tray, dock, and application launcher. As well as the in the "services" listing for spotify in the Nuvola player app

**Comment by fenryxo** [comment]
That's interesting. How does an icon image `icon.png` in directory `/usr/share/nuvolaplayer3/web_apps/spotify` look? Is it also broken?

**Comment by sh4wn** [comment]
The same happens to the Google Play icon.

![screenshot from 2015-12-04 17-04-16](https://cloud.githubusercontent.com/assets/24530/11594220/13fe2264-9aa9-11e5-920c-82a16e04048a.png)

Which is quite obvious when you open the image:

![screenshot from 2015-12-04 17-04-53](https://cloud.githubusercontent.com/assets/24530/11594240/2f8f21b8-9aa9-11e5-8c82-1ec2cef6809a.png)

I guess the same happens with the Spotify Icon. I'm also running Arch Linux with the latest GNOME.

**Comment by fenryxo** [comment]
It looks like a bug in librsvg/rsvg-convert then. Which version do you have in your system?

**Comment by sh4wn** [comment]
I've got this version:

    rsvg-convert version 2.40.12

**Comment by fenryxo** [comment]
I build packages of scripts for Ubuntu/Debian/Fedora with librsvg 2.40.5, which works fine. It may be necessary to build PNG images with other tool than the broken rsvg-convert.

**Comment by fenryxo** [comment]
@sh4wn, could you check the latest Google Play Music script 5.11 whether its icons are build incorrectly either.

**Comment by sh4wn** [comment]
Yes, it looks fixed here on my laptop. Will check at my home computer in a
few days. Thanks!

Op za 26 dec. 2015 om 11:48 schreef Jiří Janoušek <notifications@github.com

**Comment by lennrg** [comment]
The issue is persistent on my system after upgrading to 5.11 using Google Play Music.

    Arch Linux 4.3.3-2
    Nuvolaplayer 3.0.0.r2.gd865d68-1
    Nuvola-app-google-play 5.11.r0.g2bdd8d6-1
    librsvg 2:2.40.11-1

Manually deleted /usr/share/nuvolaplayer3 and removed the player and Google Play packages before upgrading.

**Comment by fenryxo** [comment]
Hi @lennrg. @sh4wn wrote that it was OK with librsvg 2.40.12. Do you have a chance to upgrade your librsvg library?

**Comment by lennrg** [comment]
@fenryxo, I am currently completely upgraded against the Arch Linux Repository, which is 2.40.11. The current build in the repo is flagged out of date and will probably updated soon. 

I will report back as soon as it is updated.

**Comment by Celti** [comment]
librsvg in Arch was forcibly downgraded to 2.40.11 due to an [upstream bug](https://bugzilla.gnome.org/show_bug.cgi?id=759084). It was not resolved until yesterday and will not be upgraded until 2.40.14 is released.

**Comment by fenryxo** [comment]
Thanks for info, @Celti. Is there any librsvg AUR package that builds from git snapshot instead of a stable release tarball?

**Comment by fenryxo** [comment]
Hello. This issue seems to have become abandoned as nobody has responded to my request for more information I posted more than a month ago. Hereby I'm closing this ticket. Feel free to add the requested information and reopen the issue providing it is still valid. Thanks.
